### ISSUE TITLE
Not being able to connect to named host from another docker-compose service

### ISSUE THREAD

**Issue by kevinwolfcr** [neondatabase/wsproxy#3]
## Steps to reproduce

Following [this tutorial](https://gal.hagever.com/posts/running-vercel-postgres-locally), I created this file:

*docker-compose.yml*

```yml
version: "3"

services:
  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: my_db
    ports:
      - 5432:5432
  db-proxy:
    platform: linux/x86_64
    image: ghcr.io/neondatabase/wsproxy:latest
    environment:
      APPEND_PORT: db:5432
      ALLOW_ADDR_REGEX: .*
      LOG_TRAFFIC: true
    ports:
      - 5433:80
    depends_on:
      - db
```

## Expected result

My request is proxied successfully.

## Actual result

The request is not proxied, since the `APPEND_PORT` is just concatenating to the `addr` in the script. So it is trying to proxy to `localhost:5432db:5432` rather than `db:5432`

## Environment

Local development using `docker-compose` in an *Apple M1 Pro* computer (not sure if this is the issue, since I have experienced issues with docker on this architecture before).

## Logs, links

**docker logs**

```sh
docker-compose up --pull --build
[+] Running 2/2
 ✔ db-proxy Pulled                                                                                  1.4s 
 ✔ db Pulled                                                                                        4.4s 
[+] Building 0.0s (0/0)                                                                                  
[+] Running 2/1
 ✔ Container web-db-1        Recreated                                                              0.1s 
 ✔ Container web-db-proxy-1  Recreated                                                              0.0s 
Attaching to web-db-1, web-db-proxy-1
web-db-1        | 
web-db-1        | PostgreSQL Database directory appears to contain a database; Skipping initialization
web-db-1        | 
web-db-1        | 2023-06-24 18:39:13.993 UTC [1] LOG:  starting PostgreSQL 15.2 on aarch64-unknown-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
web-db-1        | 2023-06-24 18:39:13.993 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
web-db-1        | 2023-06-24 18:39:13.993 UTC [1] LOG:  listening on IPv6 address "::", port 5432
web-db-1        | 2023-06-24 18:39:13.995 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
web-db-1        | 2023-06-24 18:39:14.001 UTC [24] LOG:  database system was shut down at 2023-06-24 18:39:08 UTC
web-db-1        | 2023-06-24 18:39:14.007 UTC [1] LOG:  database system is ready to accept connections
web-db-proxy-1  | 2023/06/24 18:39:14 Using regex for allowed addresses: .*
web-db-proxy-1  | 2023/06/24 18:39:14 Starting server on port :80
web-db-proxy-1  | 2023/06/24 18:39:21 Got request from 172.19.0.1:45766
web-db-proxy-1  | 2023/06/24 18:39:21 Got request from 172.19.0.1:45766, proxying to localhost:5432db:5432, allowed=true, addressArg=localhost:5432, hostHeader=localhost:5433
web-db-proxy-1  | 2023/06/24 18:39:21 failed to handle websocket: dial tcp: address localhost:5432db:5432: too many colons in address
```
